image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  annotations: {}
  automount: true
  name: ""

appMessage: "Shipping Service" 
